name: Run Crawl Post Script
on:
  schedule:
    - cron: "*/30 * * * *" # Run every 30 minutes
  workflow_dispatch: # Allow manual trigger
jobs:
  run-crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Install ChromeDriver
        run: |
          # Get Chrome major version
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          echo "Chrome version: $CHROME_VERSION"
          # Fetch the latest ChromeDriver version for this Chrome version
          DRIVER_VERSION=$(curl -sS https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_${CHROME_VERSION})
          echo "ChromeDriver version: $DRIVER_VERSION"
          # Download ChromeDriver from the new Chrome for Testing URL
          wget -N https://storage.googleapis.com/chrome-for-testing-public/${DRIVER_VERSION}/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          chmod +x chromedriver-linux64/chromedriver
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
      - name: Run crawl script
        run: python crawl_post_user.py